### ISSUE TITLE
直播相关的代码貌似没有开源？

### ISSUE THREAD

**Issue by songquanpeng** [icepie/jojo-live#1]
比较好奇这方面的实现。

**Comment by icepie** [comment]
会有的，正在改啦，现在实现得比较丑，等我完善一下就发上来

主要用的rtmp推流

**Comment by songquanpeng** [comment]
期待

**Comment by icepie** [comment]
https://github.com/icepie/jojo-stream 

我先简单放上来, 不太完善, 要用的话手动替换源码里的推流地址再编译

等我这几天忙完完善一下

> 会有的，正在改啦，现在实现得比较丑，等我完善一下就发上来
> 
> 主要用的rtmp推流

**Comment by songquanpeng** [comment]
好的，继续期待
